### ISSUE TITLE
Strip whitespace at end of secret

### ISSUE THREAD

**Issue by Joe-Heffer-Shef** [Fischerfredl/get-docker-secret#2]
This line will cause an error if the secret intentionally contains a space at the end

https://github.com/Fischerfredl/get-docker-secret/blob/master/get_docker_secret.py#L32

consider using `readline().rstrip('\n')` or similar

**Comment by Fischerfredl** [comment]
I just checked if there might be conflicting requirements here because the commit e556ccd mentions to specifically strip for whitespace. However in the corresponding PR #1 the submitter only talks about protecting against newlines. 

I find your approach more sane and will update the package accordingly. Thanks for the issue.

**Comment by Fischerfredl** [comment]
It has been a while since I have been working with docker. You propose to use `readline()` instead of `read()` to fetch the file contents. Are multiline secrets possible in docker? Then I am tempted to leave `read()` and only strip the end of the file from newlines. Result:

```diff
-            value = secret_file.read().strip()
+            value = secret_file.read().rstrip('\n')
```

What do you think?

**Comment by Joe-Heffer-Shef** [comment]
Hi, yes `readline` isn't appropriate because you might want multi-line secrets (such as SSH keys, etc.)

Yes I think `value = secret_file.read().rstrip('\n')` looks good
